version: '2'

volumes:
    db-data:

services:
    workspace:
        image: stefanorg/data
        volumes:
            #container configuration
            - "${HOME}/.composer:/home/dockerdev/.composer"
            - "${HOME}/.ssh:/home/dockerdev/.ssh"
            - ./logs:/opt/wildfly/logs

    db:
        image: percona/percona-server:latest
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: appuser
            MYSQL_PASSWORD: apppwd
            MYSQL_ROOT_PASSWORD: 123

    wildfly:
        build: docker/wildfly
        expose:
            - "8080"
            - "8443"
            - "9990"
        ports:
            - "8080:8080"
            - "8443:8443"
            - "9990:9990"
        volumes_from:
            - workspace
        links:
            - db
        environment:
            JBOSS_LOG_DIR: /opt/wildfly/logs